server:
  port: 9090

spring:
  application:
    name: "users"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3309/usersdb
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7080/realms/master
          jwk-set-uri: http://localhost:7080/realms/master/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: always
      readiness-state:
        enabled: true
      liveness-state:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "users"
    description: "Eazy Bank User Management Application"
    version: "1.0.0"

logging:
  level:
    org.keycloak: DEBUG
    com:
      ms:
        users: DEBUG

keycloak:
  auth-server-url: http://localhost:7080
  realm: master
  client-id: users-service-client
  client-secret: szmCOx4BJdzMjvEbOOr2pmfXkSYPheQO
  public-client: false